apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: load-balanced-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-balanced-app
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
