name: Build and Deploy Docker Image to Linode Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/load-balanced-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Authenticate with Linode Kubernetes
        env:
          K8S_API_URL: ${{ secrets.LINODE_K8S_API_URL }}
          K8S_TOKEN: ${{ secrets.LINODE_K8S_TOKEN }}
        run: |
          mkdir -p ~/.kube
          echo "
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              server: ${K8S_API_URL}
              insecure-skip-tls-verify: true
            name: linode-cluster
          contexts:
          - context:
              cluster: linode-cluster
              user: linode-user
            name: linode-context
          current-context: linode-context
          users:
          - name: linode-user
            user:
              token: ${K8S_TOKEN}
          " > ~/.kube/config

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/
