name: Build and Deploy Docker Image to Linode Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/load-balanced-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Authenticate with Linode Kubernetes
        run: |
          echo ${{ secrets.LINODE_K8S_TOKEN }} | kubectl config set-credentials linode --token=$(cat -)
          kubectl config set-cluster linode-cluster --server=${{ secrets.LINODE_K8S_API_URL }} --insecure-skip-tls-verify=true
          kubectl config set-context linode --cluster=linode-cluster --user=linode
          kubectl config use-context linode

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/
